### ISSUE TITLE
Hook to Vanishing plugin

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/AzLink#13]
Hello,

I had already made an issue about this a few months ago, it worked, but now it doesn't work anymore :/
I use [PremiumVanish 2.7.12](https://www.spigotmc.org/resources/14404/) (one of the most popular plugins)
And AzLink 1.1.0

**Comment by MrMicky-FR** [comment]
The commit above should fix the issue, and it will be available in the next release of AzLink.

Until the next release, you can use the build from GitHub Actions available [here](https://github.com/Azuriom/AzLink/actions/runs/1989262564).
