### ISSUE TITLE
Menu suggestion

### ISSUE THREAD

**Issue by BrayaanPS** [Azuriom/AzLink#14]
Could you implement an option that when using a command opens a menu showing you the categories and packages of the store?
Example:
Using the /buy command will open a menu with the store pages.
![image](https://user-images.githubusercontent.com/30274810/178151800-ad670293-da99-43a2-8928-ca790cb9d356.png)
Then select a category to show you the packages.
![image](https://user-images.githubusercontent.com/30274810/178151825-788bbb9d-5836-4c46-a350-a6e31d6f7155.png)
and when you select one I will send you a message in the chat with the direct link. 
![image](https://user-images.githubusercontent.com/30274810/178151873-7f004c27-7ef5-4e47-a2d9-944a8fcb61eb.png)

**Comment by MrMicky-FR** [comment]
IMHO this would be more suitable in a separate plugin
