### ISSUE TITLE
[AzLink] Unable to send data to the website: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by Striker-Qc** [Azuriom/AzLink#19]
i got that error on the version 1.19.3 of paper

**Comment by Striker-Qc** [comment]
i got it after setup the access with the version 1.0.14 of azuriom

**Comment by MrMicky-FR** [comment]
Seems like AzLink can’t connect to your website. If you are using Cloudflare, make sure to read [our FAQ](https://azuriom.com/en/docs/faq), otherwise check that there is no firewall blocking AzLink connections
