### ISSUE TITLE
Support Velocity LimboAuth

### ISSUE THREAD

**Issue by TheMrMes109** [Azuriom/AzLink#24]
Good day.
I would like to see in the version for Velocity
registration support in LimboAuth (same as Spigot AuthMe).
The LimboAuth source code is on GitHub - https://github.com/Elytrium/LimboAuth

**Comment by MrMicky-FR** [comment]
Is there any API documentation and Maven repository ? Can't find any english documentation

**Comment by TheMrMes109** [comment]
Wrote a ticket to the author of the plugin

**Comment by Wgis** [comment]
@MrMicky-FR https://github.com/Elytrium/LimboAuth

**Comment by MrMicky-FR** [comment]
> @MrMicky-FR https://github.com/Elytrium/LimboAuth

This link is already provided in the first message and doesn’t answer my question

**Comment by Wgis** [comment]
Sorry, it's awesome if you can make it!

**Comment by MrMicky-FR** [comment]
The Maven repo is https://maven.elytrium.net/ : https://maven.elytrium.net/#/repo/net/elytrium/limboauth

**Comment by Wgis** [comment]
Needs dig this events for realize:
https://github.com/Elytrium/LimboAuth/tree/master/src/main/java/net/elytrium/limboauth/event

PasswordChangeEvent suggested for LimboAuth

**Comment by TheMrMes109** [comment]
Add password change) ?
When changing the password on the server on the site, the password is not updated

**Comment by MrMicky-FR** [comment]
> Add password change) ?
> When changing the password on the server on the site, the password is not updated

We need the new version of LimboAuth in the Maven repository ( https://maven.elytrium.net/#/repo/net/elytrium/limboauth ), I’ve asked on Discord and I’m waiting an answer :)
