### ISSUE TITLE
Unable to send data to the website

### ISSUE THREAD

**Issue by xlanyleeet** [Azuriom/AzLink#25]
Hey, i have this error:
[AzLink] Unable to send data to the website: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

how to fix?

**Comment by MrMicky-FR** [comment]
Hi, this issue is usually caused by a firewall or or proxy on your website that blocks/changes the AzLink request but still returns a 200 HTTP status code.

Disabling it or whitelisting your server IP (where AzLink is installed) should solve this
