### ISSUE TITLE
Support nLogin

### ISSUE THREAD

**Issue by BAD7777** [Azuriom/AzLink#30]
Good day.

I would like to suggest adding registration support in the Velocity version using nLogin (similar to Spigot AuthMe).
Information on API usage is available on their website: https://en.docs.nickuc.com/development/usage
nLogin Web is also available on their website: https://en.docs.nickuc.com/development/nlogin-web
You can find the JavaDocs on the following website: https://jd.nickuc.com/nlogin/

Thank you for your attention to this request.

**Comment by MrMicky-FR** [comment]
Unfortunately after a closer look, seems like the API doesn't give a way to retrieve the user's password, and the plugin is hidden inside a `plugin.bin` file with bad obfuscation that prevent accessing the plugin internals through reflection. So we don't have any way to do this without dark magic...

I would suggest using an open-source plugin like [LimboAuth](https://github.com/Elytrium/LimboAuth) where at least the code can be audited freely (security by obscurity is never a good idea)
