### ISSUE TITLE
Add support for LimboAuth

### ISSUE THREAD

**Issue by Futuraura** [Azuriom/AzLink#36]
Add AzLink support for [LimboAuth](https://github.com/Elytrium/LimboAuth), because AuthMe is too outdated and either nLogin or LimboAuth are way better, because both have better security, more frequent updates and more features.

**Comment by MrMicky-FR** [comment]
LimboAuth is already supported

**Comment by Futuraura** [comment]
How do I set it up?
And I think i should rename this into "better support with auth plugins"

**Comment by MrMicky-FR** [comment]
It’s automatically enabled when AzLink and LimboAuth are installed on Velocity

> And I think i should rename this into "better support with auth plugins"

I’m not sure to understand what to rename

**Comment by Futuraura** [comment]
Nvm, I'll open a new feature request in est. 2 days.
I'll try to make a nice optimized plan of how server would talk to website for website and the server to be more "integrated", cause the password changing thing really got me thinking about it.

**Comment by MrMicky-FR** [comment]
The password change will be handled once the [LimboAuth Maven repo](https://maven.elytrium.net/#/repo/net/elytrium/limboauth) will be updated to include the `ChangePasswordEvent`. Nothing fancy to plan here :)
