### ISSUE TITLE
Unable to send data to the website: java.io.IOException: Invalid response code (403 - Forbidden)

### ISSUE THREAD

**Issue by Phoetrix** [Azuriom/AzLink#39]
Bonjour

Lorsque j'essaie la commande "/azlink setup" suivi du lien du site avec le code je reçois l'erreur suivante : 
ERROR [AzLink] Unable to send data to the website: java.io.IOException: Invalid response code (403 - Forbidden)

Avez-vous une idée de l'origine du problème ? Je n'ai pas plus de détails
J'utilise la version de Paper pour Minecraft 1.20.4 avec la dernière version Legacy de AzLink

Merci

**Comment by MrMicky-FR** [comment]
Refaire la commande de link donnée sur le panel admin devrait régler ce problème
