### ISSUE TITLE
adding features with discord and minecraft

### ISSUE THREAD

**Issue by xlanyleeet** [Azuriom/AzLink#41]
1. add placeholder discord nickname when you link discord and site
2. add linkaccount command with site and server

**Comment by MrMicky-FR** [comment]
You should directly use a registration method such as AuthMe/LimboAuth (can be enabled in the AzLink config, designed for offline-mode servers) or Microsoft (for online-mode servers), so accounts are automatically created for users, which doesn't require a manual link process
