### ISSUE TITLE
Add support for LibreLogin

### ISSUE THREAD

**Issue by xlanyleeet** [Azuriom/AzLink#42]
Here wiki: https://github.com/kyngs/LibreLogin/wiki/Basic-API-Information
Here API: https://github.com/kyngs/LibreLogin/tree/master/API/src/main/java/xyz/kyngs/librelogin/api/event/events

**Comment by MrMicky-FR** [comment]
I don’t see any way to retrieve the plain password in the events before it’s hashed. It is required as the hashing function on the plugin may not be the same as on the one on the server, so the password is transmitted in plain (but over HTTPS for security) to the website and then hashed on the website

**Comment by xlanyleeet** [comment]
I will ask the plugin developer about it, maybe he will tell me where to go

**Comment by xlanyleeet** [comment]
![image](https://github.com/Azuriom/AzLink/assets/61755593/935fe23b-f733-4085-aa58-8edb181ebef9)
((
