### ISSUE TITLE
Unable to send data to the website: java.net.SocketTimeoutException: Read timed out.

### ISSUE THREAD

**Issue by Zinnorov** [Azuriom/AzLink#43]
I haven't set up Cloudflare yet.

According to the hosting provider:

I do not observe any blocking on the server side.
There are no errors in the site logs either.
In the logs of requests to the site, there is a large number of requests from AzLink java v1.3.5, and the server responded with the code 200/204 in all cases.

**Comment by Zinnorov** [comment]
"/azlink status" returns this - Linked to the website successfully.

**Comment by Zinnorov** [comment]
The issue was closed unintentionally.
The "/azlink status" returns - Linked to the website successfully.

**Comment by MrMicky-FR** [comment]
Can you send me a private message on Discord `@mrmicky`please for easier debugging (my DM are open, no need for a friend request), thanks!

**Comment by MrMicky-FR** [comment]
Closing this for now as it doesn't seem related to an issue with Azuriom/AzLink
