### ISSUE TITLE
rajout placeholders 

### ISSUE THREAD

**Issue by elona6869** [Azuriom/AzLink#47]
des placeholders qui sont connecter au vote du site qui peuve etre aficher sur le serveur minecraft exemple
%az_vote_#% pour le nombre de vote a aficher et le "#" pour le numero de placement dans le top a inscrire a la place de ca et
%az_topvote_#% pour le nom du joueur qui aura le clasement inscrit
Merci pour ce que vous faite

**Comment by MrMicky-FR** [comment]
Merci de vérifier parmi les issues déjà ouvertes avant de poster (il y en a 2, ça ne devrait pas prendre plus de 30 secondes), car c’est déjà proposé en #16

Duplicate of #16
