### ISSUE TITLE
Rust / Rcon platform

### ISSUE THREAD

**Issue by Doldak** [Azuriom/AzLink#8]
can you write a simple Rust/Rcon platform conection?

**Comment by MrMicky-FR** [comment]
Rust RCON is [already supported](https://github.com/Azuriom/Azuriom/blob/4bf8aa2a6fa29fa2b010b56dd10aed2388acad1d/app/Games/Steam/Servers/RustRcon.php) in Azuriom, you just need to select the game Rust during the installation.

**Comment by Doldak** [comment]
its not that what i mean...
you can check "send when user is online" this required only azlink....

**Comment by MrMicky-FR** [comment]
AzLink is now available as an Oxide (uMod) plugin: https://github.com/Azuriom/AzLink-Oxide ! It will be compatible with the next Azuriom release
